name: Build WDA IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Appium WDA
        uses: actions/checkout@v4
        with:
          repository: appium/WebDriverAgent
          ref: refs/heads/main

      - name: Build WDA
        run: |
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./build \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=000000

      - name: Generate IPA
        run: |
          mkdir Payload
          cp -r ./build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WDA.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: WDA
          path: WDA.ipa
