name: Build WDA IPA

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build WDA
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
        run: |
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -derivedDataPath ./build \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }}

      - name: Generate IPA
        run: |
          mkdir Payload
          cp -r ./build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WDA.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: WDA-${{ github.run_id }}
          path: WDA.ipa
